theme:jekyll_theme_minimal
title: 'LAPD - Violence Prediction'
description: This regression model uses labelling on data available at point of call to predict whether or not violence is involved in a call.
